/*SDK: Fix 2 toLowerCase using default locale.

Change-Id:I33fbad62b3df21068c64ef434d82682d4d192560*/
//Synthetic comment -- diff --git a/anttasks/src/com/android/ant/MultiFilesTask.java b/anttasks/src/com/android/ant/MultiFilesTask.java
//Synthetic comment -- index 3abcafc..7d4a884 100644

//Synthetic comment -- @@ -27,6 +27,7 @@
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
//Synthetic comment -- @@ -85,7 +86,7 @@
// The gen folder may contain other dependency files not generated by this particular
// processor.
// We only care if the first pre-rep is of the right extension.
            if (sourceFilePath.toLowerCase().endsWith("." + extension)) {
// remove from the list of sourceFiles to mark as "processed" (but not compiled
// yet, that'll be done by adding it to toCompile)
String sourceFolder = sourceFiles.get(sourceFilePath);








//Synthetic comment -- diff --git a/anttasks/src/com/android/ant/NewSetupTask.java b/anttasks/src/com/android/ant/NewSetupTask.java
//Synthetic comment -- index 4706084..c74b946 100644

//Synthetic comment -- @@ -48,6 +48,7 @@
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathExpressionException;
//Synthetic comment -- @@ -461,7 +462,7 @@
FilenameFilter filter = new FilenameFilter() {
@Override
public boolean accept(File dir, String name) {
                return name.toLowerCase().endsWith(".jar");
}
};








