/*SdkManager method to query known build-tools.

Also refactors FullRevision and MajorRevision to move them
out of internal.repository. Their API is not going to change.

Change-Id:I3eab40fc2c4844a9ddb4fcadd9eb0c571fc437d4*/
//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/BuildToolInfo.java b/sdklib/src/main/java/com/android/sdklib/BuildToolInfo.java
new file mode 100755
//Synthetic comment -- index 0000000..4c75821

//Synthetic comment -- @@ -0,0 +1,170 @@








//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/SdkManager.java b/sdklib/src/main/java/com/android/sdklib/SdkManager.java
//Synthetic comment -- index 0a5e06b..f8c481b 100644

//Synthetic comment -- @@ -33,10 +33,14 @@
import com.android.sdklib.internal.repository.packages.ExtraPackage;
import com.android.sdklib.internal.repository.packages.Package;
import com.android.sdklib.internal.repository.packages.PlatformToolPackage;
import com.android.sdklib.repository.PkgProps;
import com.android.utils.ILogger;
import com.android.utils.NullLogger;
import com.android.utils.Pair;

import java.io.File;
import java.io.FileInputStream;
//Synthetic comment -- @@ -106,8 +110,11 @@
private final String mOsSdkPath;
/** Valid targets that have been loaded. Can be empty but not null. */
private IAndroidTarget[] mTargets = new IAndroidTarget[0];
/** A map to keep information on directories to see if they change later. */
    private final Map<File, DirInfo> mTargetDirs = new HashMap<File, SdkManager.DirInfo>();

/**
* Create a new {@link SdkManager} instance.
//Synthetic comment -- @@ -146,10 +153,12 @@
*/
public void reloadSdk(ILogger log) {
// get the current target list.
        mTargetDirs.clear();
        ArrayList<IAndroidTarget> targets = new ArrayList<IAndroidTarget>();
        loadPlatforms(mOsSdkPath, targets, mTargetDirs, log);
        loadAddOns(mOsSdkPath, targets, mTargetDirs, log);

// For now replace the old list with the new one.
// In the future we may want to keep the current objects, so that ADT doesn't have to deal
//Synthetic comment -- @@ -158,13 +167,14 @@
// sort the targets/add-ons
Collections.sort(targets);
setTargets(targets.toArray(new IAndroidTarget[targets.size()]));

// load the samples, after the targets have been set.
initializeSamplePaths(log);
}

/**
     * Checks whether any of the SDK platforms/add-ons have changed on-disk
* since we last loaded the SDK. This does not reload the SDK nor does it
* change the underlying targets.
*
//Synthetic comment -- @@ -174,16 +184,22 @@
Set<File> visited = new HashSet<File>();
boolean changed = false;

        File platformFolder = new File(mOsSdkPath, SdkConstants.FD_PLATFORMS);
        if (platformFolder.isDirectory()) {
            File[] platforms  = platformFolder.listFiles();
            if (platforms != null) {
                for (File platform : platforms) {
                    if (!platform.isDirectory()) {
continue;
}
                    visited.add(platform);
                    DirInfo dirInfo = mTargetDirs.get(platform);
if (dirInfo == null) {
// This is a new platform directory.
changed = true;
//Synthetic comment -- @@ -193,43 +209,18 @@
if (changed) {
if (DEBUG) {
System.out.println("SDK changed due to " +              //$NON-NLS-1$
                                (dirInfo != null ? dirInfo.toString() : platform.getPath()));
}
}
}
}
}

        File addonFolder = new File(mOsSdkPath, SdkConstants.FD_ADDONS);

        if (!changed && addonFolder.isDirectory()) {
            File[] addons  = addonFolder.listFiles();
            if (addons != null) {
                for (File addon : addons) {
                    if (!addon.isDirectory()) {
                        continue;
                    }
                    visited.add(addon);
                    DirInfo dirInfo = mTargetDirs.get(addon);
                    if (dirInfo == null) {
                        // This is a new add-on directory.
                        changed = true;
                    } else {
                        changed = dirInfo.hasChanged();
                    }
                    if (changed) {
                        if (DEBUG) {
                            System.out.println("SDK changed due to " +              //$NON-NLS-1$
                                (dirInfo != null ? dirInfo.toString() : addon.getPath()));
                        }
                    }
                }
            }
        }

if (!changed) {
// Check whether some pre-existing target directories have vanished.
            for (File previousDir : mTargetDirs.keySet()) {
if (!visited.contains(previousDir)) {
// This directory is no longer present.
changed = true;
//Synthetic comment -- @@ -272,6 +263,29 @@
mTargets = targets;
}

/**
* Returns a target from a hash that was generated by {@link IAndroidTarget#hashString()}.
*
//Synthetic comment -- @@ -461,7 +475,8 @@
private static void loadPlatforms(
String sdkOsPath,
ArrayList<IAndroidTarget> targets,
            Map<File, DirInfo> dirInfos, ILogger log) {
File platformFolder = new File(sdkOsPath, SdkConstants.FD_PLATFORMS);

if (platformFolder.isDirectory()) {
//Synthetic comment -- @@ -801,7 +816,8 @@
private static void loadAddOns(
String osSdkPath,
ArrayList<IAndroidTarget> targets,
            Map<File, DirInfo> dirInfos, ILogger log) {
File addonFolder = new File(osSdkPath, SdkConstants.FD_ADDONS);

if (addonFolder.isDirectory()) {
//Synthetic comment -- @@ -1230,6 +1246,94 @@
return null;
}

// -------------

public static class LayoutlibVersion implements Comparable<LayoutlibVersion> {








//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/BuildToolPackage.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/BuildToolPackage.java
//Synthetic comment -- index 23a6eec..23fe5ac 100755

//Synthetic comment -- @@ -23,9 +23,10 @@
import com.android.sdklib.internal.repository.IDescription;
import com.android.sdklib.internal.repository.archives.Archive.Arch;
import com.android.sdklib.internal.repository.archives.Archive.Os;
import com.android.sdklib.internal.repository.packages.FullRevision.PreviewComparison;
import com.android.sdklib.internal.repository.sources.SdkSource;
import com.android.sdklib.repository.PkgProps;

import org.w3c.dom.Node;









//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/FullRevisionPackage.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/FullRevisionPackage.java
//Synthetic comment -- index 698b211..bf63752 100755

//Synthetic comment -- @@ -18,10 +18,11 @@

import com.android.sdklib.internal.repository.archives.Archive.Arch;
import com.android.sdklib.internal.repository.archives.Archive.Os;
import com.android.sdklib.internal.repository.packages.FullRevision.PreviewComparison;
import com.android.sdklib.internal.repository.sources.SdkSource;
import com.android.sdklib.repository.PkgProps;
import com.android.sdklib.repository.SdkRepoConstants;

import org.w3c.dom.Node;









//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/IFullRevisionProvider.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/IFullRevisionProvider.java
//Synthetic comment -- index 10f66d2..8a6a15e 100755

//Synthetic comment -- @@ -16,7 +16,9 @@

package com.android.sdklib.internal.repository.packages;

import com.android.sdklib.internal.repository.packages.FullRevision.PreviewComparison;











//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/IMinPlatformToolsDependency.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/IMinPlatformToolsDependency.java
//Synthetic comment -- index d17b800..b8aae78 100755

//Synthetic comment -- @@ -16,6 +16,7 @@

package com.android.sdklib.internal.repository.packages;

import com.android.sdklib.repository.SdkRepoConstants;

/**








//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/IMinToolsDependency.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/IMinToolsDependency.java
//Synthetic comment -- index 064f1d3..d0f9e8d 100755

//Synthetic comment -- @@ -16,6 +16,7 @@

package com.android.sdklib.internal.repository.packages;

import com.android.sdklib.repository.SdkRepoConstants;

/**








//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/MajorRevisionPackage.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/MajorRevisionPackage.java
//Synthetic comment -- index 4591297..45a018c 100755

//Synthetic comment -- @@ -19,6 +19,8 @@
import com.android.sdklib.internal.repository.archives.Archive.Arch;
import com.android.sdklib.internal.repository.archives.Archive.Os;
import com.android.sdklib.internal.repository.sources.SdkSource;
import com.android.sdklib.repository.PkgProps;
import com.android.sdklib.repository.SdkRepoConstants;









//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/MinToolsPackage.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/MinToolsPackage.java
//Synthetic comment -- index a608a3c..049137e 100755

//Synthetic comment -- @@ -19,6 +19,7 @@
import com.android.sdklib.internal.repository.archives.Archive.Arch;
import com.android.sdklib.internal.repository.archives.Archive.Os;
import com.android.sdklib.internal.repository.sources.SdkSource;
import com.android.sdklib.repository.PkgProps;
import com.android.sdklib.repository.SdkRepoConstants;









//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/Package.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/Package.java
//Synthetic comment -- index 397cce1..1ca90dd 100755

//Synthetic comment -- @@ -32,6 +32,7 @@
import com.android.sdklib.internal.repository.sources.SdkRepoSource;
import com.android.sdklib.internal.repository.sources.SdkSource;
import com.android.sdklib.io.IFileOp;
import com.android.sdklib.repository.PkgProps;
import com.android.sdklib.repository.SdkAddonConstants;
import com.android.sdklib.repository.SdkRepoConstants;








//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/PackageParserUtils.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/PackageParserUtils.java
//Synthetic comment -- index a6986e1..a71247b 100755

//Synthetic comment -- @@ -16,6 +16,7 @@

package com.android.sdklib.internal.repository.packages;

import com.android.sdklib.repository.SdkRepoConstants;

import org.w3c.dom.Node;








//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/PlatformToolPackage.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/PlatformToolPackage.java
//Synthetic comment -- index 29828f0..0930f86 100755

//Synthetic comment -- @@ -26,8 +26,8 @@
import com.android.sdklib.internal.repository.archives.Archive;
import com.android.sdklib.internal.repository.archives.Archive.Arch;
import com.android.sdklib.internal.repository.archives.Archive.Os;
import com.android.sdklib.internal.repository.packages.FullRevision.PreviewComparison;
import com.android.sdklib.internal.repository.sources.SdkSource;

import org.w3c.dom.Node;









//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/ToolPackage.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/ToolPackage.java
//Synthetic comment -- index ddf71d8..2f0094d 100755

//Synthetic comment -- @@ -26,10 +26,11 @@
import com.android.sdklib.internal.repository.archives.Archive;
import com.android.sdklib.internal.repository.archives.Archive.Arch;
import com.android.sdklib.internal.repository.archives.Archive.Os;
import com.android.sdklib.internal.repository.packages.FullRevision.PreviewComparison;
import com.android.sdklib.internal.repository.sources.SdkSource;
import com.android.sdklib.repository.PkgProps;
import com.android.sdklib.repository.SdkRepoConstants;
import com.android.sdklib.util.GrabProcessOutput;
import com.android.sdklib.util.GrabProcessOutput.IProcessOutput;
import com.android.sdklib.util.GrabProcessOutput.Wait;








//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/updater/PkgItem.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/updater/PkgItem.java
//Synthetic comment -- index 9e0912e..c5eb07e 100755

//Synthetic comment -- @@ -17,11 +17,11 @@
package com.android.sdklib.internal.repository.updater;

import com.android.sdklib.internal.repository.archives.Archive;
import com.android.sdklib.internal.repository.packages.FullRevision;
import com.android.sdklib.internal.repository.packages.IAndroidVersionProvider;
import com.android.sdklib.internal.repository.packages.Package;
import com.android.sdklib.internal.repository.packages.Package.UpdateInfo;
import com.android.sdklib.internal.repository.sources.SdkSource;

/**
* A {@link PkgItem} represents one main {@link Package} combined with its state








//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/updater/SdkUpdaterLogic.java b/sdklib/src/main/java/com/android/sdklib/internal/repository/updater/SdkUpdaterLogic.java
//Synthetic comment -- index be214f7..006e45f 100755

//Synthetic comment -- @@ -24,7 +24,6 @@
import com.android.sdklib.internal.repository.packages.BuildToolPackage;
import com.android.sdklib.internal.repository.packages.DocPackage;
import com.android.sdklib.internal.repository.packages.ExtraPackage;
import com.android.sdklib.internal.repository.packages.FullRevision;
import com.android.sdklib.internal.repository.packages.IAndroidVersionProvider;
import com.android.sdklib.internal.repository.packages.IExactApiLevelDependency;
import com.android.sdklib.internal.repository.packages.IMinApiLevelDependency;
//Synthetic comment -- @@ -41,6 +40,7 @@
import com.android.sdklib.internal.repository.packages.ToolPackage;
import com.android.sdklib.internal.repository.sources.SdkSource;
import com.android.sdklib.internal.repository.sources.SdkSources;

import java.util.ArrayList;
import java.util.Arrays;








//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/FullRevision.java b/sdklib/src/main/java/com/android/sdklib/repository/FullRevision.java
similarity index 99%
rename from sdklib/src/main/java/com/android/sdklib/internal/repository/packages/FullRevision.java
rename to sdklib/src/main/java/com/android/sdklib/repository/FullRevision.java
//Synthetic comment -- index 67852ff..0986a34 100755

//Synthetic comment -- @@ -14,7 +14,7 @@
* limitations under the License.
*/

package com.android.sdklib.internal.repository.packages;

import com.android.annotations.NonNull;









//Synthetic comment -- diff --git a/sdklib/src/main/java/com/android/sdklib/internal/repository/packages/MajorRevision.java b/sdklib/src/main/java/com/android/sdklib/repository/MajorRevision.java
similarity index 96%
rename from sdklib/src/main/java/com/android/sdklib/internal/repository/packages/MajorRevision.java
rename to sdklib/src/main/java/com/android/sdklib/repository/MajorRevision.java
//Synthetic comment -- index eefda3b..c953e84 100755

//Synthetic comment -- @@ -14,7 +14,7 @@
* limitations under the License.
*/

package com.android.sdklib.internal.repository.packages;

import com.android.annotations.NonNull;









//Synthetic comment -- diff --git a/sdklib/src/test/java/com/android/sdklib/SdkManagerTest.java b/sdklib/src/test/java/com/android/sdklib/SdkManagerTest.java
//Synthetic comment -- index 487a96a..9efe001 100755

//Synthetic comment -- @@ -20,8 +20,12 @@
import com.android.SdkConstants;
import com.android.sdklib.ISystemImage.LocationType;
import com.android.sdklib.SdkManager.LayoutlibVersion;

import java.util.Arrays;
import java.util.regex.Pattern;

public class SdkManagerTest extends SdkManagerTestCase {
//Synthetic comment -- @@ -41,6 +45,37 @@
assertSame(lv, sdkman.getMaxLayoutlibVersion());
}

public void testSdkManager_SystemImage() throws Exception {
SdkManager sdkman = getSdkManager();
assertEquals("[PlatformTarget API 0 rev 1]", Arrays.toString(sdkman.getTargets()));








//Synthetic comment -- diff --git a/sdklib/src/test/java/com/android/sdklib/SdkManagerTestCase.java b/sdklib/src/test/java/com/android/sdklib/SdkManagerTestCase.java
//Synthetic comment -- index 9ca4c32..030f6c9 100755

//Synthetic comment -- @@ -256,6 +256,8 @@
new File(buildToolsDir, SdkConstants.FN_AAPT).createNewFile();
new File(buildToolsDir, SdkConstants.FN_AIDL).createNewFile();
new File(buildToolsDir, SdkConstants.FN_DX).createNewFile();
}
}









//Synthetic comment -- diff --git a/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/FullRevisionPackageTest.java b/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/FullRevisionPackageTest.java
//Synthetic comment -- index 9bf2703..621ac0a 100755

//Synthetic comment -- @@ -16,6 +16,7 @@

package com.android.sdklib.internal.repository.packages;

import com.android.sdklib.repository.PkgProps;

import java.util.ArrayList;








//Synthetic comment -- diff --git a/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/FullRevisionTest.java b/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/FullRevisionTest.java
//Synthetic comment -- index 07e8186..2803052 100755

//Synthetic comment -- @@ -16,6 +16,8 @@

package com.android.sdklib.internal.repository.packages;

import java.util.Arrays;

import junit.framework.TestCase;








//Synthetic comment -- diff --git a/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MajorRevisionTest.java b/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MajorRevisionTest.java
//Synthetic comment -- index b77caad..b6dc5d4 100755

//Synthetic comment -- @@ -16,6 +16,9 @@

package com.android.sdklib.internal.repository.packages;

import junit.framework.TestCase;

public class MajorRevisionTest extends TestCase {








//Synthetic comment -- diff --git a/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MockBuildToolPackage.java b/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MockBuildToolPackage.java
//Synthetic comment -- index 85fb617..3150fb2 100755

//Synthetic comment -- @@ -19,6 +19,7 @@
import com.android.sdklib.internal.repository.archives.Archive.Arch;
import com.android.sdklib.internal.repository.archives.Archive.Os;
import com.android.sdklib.internal.repository.sources.SdkSource;

/**
* A mock {@link BuildToolPackage} for testing.








//Synthetic comment -- diff --git a/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MockPlatformPackage.java b/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MockPlatformPackage.java
//Synthetic comment -- index dd744ec..ccd2048 100755

//Synthetic comment -- @@ -20,6 +20,7 @@
import com.android.sdklib.internal.repository.MockPlatformTarget;
import com.android.sdklib.internal.repository.packages.PlatformPackage;
import com.android.sdklib.internal.repository.sources.SdkSource;
import com.android.sdklib.repository.PkgProps;

import java.util.Properties;








//Synthetic comment -- diff --git a/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MockPlatformToolPackage.java b/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MockPlatformToolPackage.java
//Synthetic comment -- index e742dee..734a596 100755

//Synthetic comment -- @@ -19,6 +19,7 @@
import com.android.sdklib.internal.repository.archives.Archive.Arch;
import com.android.sdklib.internal.repository.archives.Archive.Os;
import com.android.sdklib.internal.repository.sources.SdkSource;

/**
* A mock {@link PlatformToolPackage} for testing.








//Synthetic comment -- diff --git a/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MockToolPackage.java b/sdklib/src/test/java/com/android/sdklib/internal/repository/packages/MockToolPackage.java
//Synthetic comment -- index 0382f34..3503621 100755

//Synthetic comment -- @@ -20,6 +20,7 @@
import com.android.sdklib.internal.repository.archives.Archive.Os;
import com.android.sdklib.internal.repository.packages.ToolPackage;
import com.android.sdklib.internal.repository.sources.SdkSource;
import com.android.sdklib.repository.PkgProps;

import java.util.Properties;







