/*Corrected repeat count for key repeat in input device.

Previously the key event repeat count was always zero when the repeated
key down events was generated by the input device in the Linux kernel.

Change-Id:I9e295ca41ffe7324f54083f0a493e073187feb28*/
//Synthetic comment -- diff --git a/phone/com/android/internal/policy/impl/PhoneWindowManager.java b/phone/com/android/internal/policy/impl/PhoneWindowManager.java
//Synthetic comment -- index 382c833..dec495d 100755

//Synthetic comment -- @@ -274,6 +274,9 @@
ShortcutManager mShortcutManager;
PowerManager.WakeLock mBroadcastWakeLock;

class SettingsObserver extends ContentObserver {
SettingsObserver(Handler handler) {
super(handler);
//Synthetic comment -- @@ -1808,6 +1811,18 @@
boolean down = event.value != 0;

if (type == RawInputEvent.EV_KEY) {
if (code == KeyEvent.KEYCODE_ENDCALL
|| code == KeyEvent.KEYCODE_POWER) {
if (down) {
//Synthetic comment -- @@ -1891,7 +1906,7 @@
// only do it if the showing app doesn't process the key on its own.
KeyEvent keyEvent = new KeyEvent(event.when, event.when,
down ? KeyEvent.ACTION_DOWN : KeyEvent.ACTION_UP,
                            code, 0);
mBroadcastWakeLock.acquire();
mHandler.post(new PassHeadsetKey(keyEvent));
}







