/*Fix SDK 21 bug: Incorrect R.java generated by ant failed to build if lib and app has same package namehttp://code.google.com/p/android/issues/detail?id=40273Cause: the R.java generated for the app is overwritten by the R.java generated for the library project if they use the same package name.

Solution: check the package name of the library project when generate R.java for it. If the package name is the same as the app's, then just skip that library project.

Change-Id:I611a489dbfd2bb3fe1e15db3b6d9f156d6e32f17*/




//Synthetic comment -- diff --git a/anttasks/src/com/android/ant/AaptExecTask.java b/anttasks/src/com/android/ant/AaptExecTask.java
old mode 100644
new mode 100755
//Synthetic comment -- index 2511500..fa03c6b

//Synthetic comment -- @@ -17,8 +17,11 @@
package com.android.ant;

import com.android.SdkConstants;
import com.android.io.FileWrapper;
import com.android.io.StreamException;
import com.android.sdklib.internal.build.SymbolLoader;
import com.android.sdklib.internal.build.SymbolWriter;
import com.android.xml.AndroidManifest;

import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.Project;
//Synthetic comment -- @@ -32,6 +35,8 @@
import java.util.List;
import java.util.Set;

import javax.xml.xpath.XPathExpressionException;

/**
* Task to execute aapt.
*
//Synthetic comment -- @@ -89,6 +94,7 @@
private int mVersionCode = 0;
private String mVersionName;
private String mManifest;
    private String mManifestPackageOriginal;
private String mManifestPackage;
private ArrayList<Path> mResources;
private String mAssets;
//Synthetic comment -- @@ -589,8 +595,16 @@
if (mManifest != null && mManifest.length() > 0) {
task.createArg().setValue("-M");
task.createArg().setValue(mManifest);
            final FileWrapper appManifest = new FileWrapper(mManifest);
            try {
                mManifestPackageOriginal = AndroidManifest.getPackage(appManifest);
            } catch (XPathExpressionException e) {
                e.printStackTrace();
            } catch (StreamException e) {
                e.printStackTrace();
            }
}
        
// Rename manifest package
if (mManifestPackage != null) {
task.createArg().setValue("--rename-manifest-package");
//Synthetic comment -- @@ -699,13 +713,17 @@
"%1$s and %2$s must contain the same number of items.",
mLibraryPackagesRefid, mLibraryRFileRefid));
}
                    
for (int i = 0 ; i < packages.length ; i++) {
                        if ((mManifestPackageOriginal != null) && mManifestPackageOriginal.equals(packages[i])) {
                            // If the library project has the same package name as the app's, then we should not
                            // overwrite the R.java generated by aapt with the one of the library.
                            continue;
                        }
File libRFile = new File(rFiles[i]);
if (libRFile.isFile()) {
SymbolLoader symbols = new SymbolLoader(libRFile);
symbols.load();
SymbolWriter writer = new SymbolWriter(mRFolder, packages[i],
symbols, symbolValues);
writer.write();







