/*Corrected repeat count for key repeat in input device.

Previously the key event repeat count was always zero when the repeated
key down events was generated by the input device in the Linux kernel.

Change-Id:I9e295ca41ffe7324f54083f0a493e073187feb28*/




//Synthetic comment -- diff --git a/phone/com/android/internal/policy/impl/PhoneWindowManager.java b/phone/com/android/internal/policy/impl/PhoneWindowManager.java
//Synthetic comment -- index 21736d5..20305d8 100755

//Synthetic comment -- @@ -258,6 +258,9 @@
PowerManager.WakeLock mBroadcastWakeLock;
PowerManager.WakeLock mDockWakeLock;

    int lastKeyCode = KeyEvent.getMaxKeyCode() + 1; //invalid code
    int keyRepeatCount = 0;

class SettingsObserver extends ContentObserver {
SettingsObserver(Handler handler) {
super(handler);
//Synthetic comment -- @@ -1688,6 +1691,18 @@
boolean down = event.value != 0;

if (type == RawInputEvent.EV_KEY) {
            if (down) {
                if (code == lastKeyCode) {
                    keyRepeatCount++;
                } else {
                    keyRepeatCount = 0;
                }
                lastKeyCode = code;
            } else {
                keyRepeatCount = 0;
                lastKeyCode = KeyEvent.getMaxKeyCode() + 1; //invalid code
            }

if (code == KeyEvent.KEYCODE_ENDCALL
|| code == KeyEvent.KEYCODE_POWER) {
if (down) {
//Synthetic comment -- @@ -1750,7 +1765,7 @@
// only do it if the showing app doesn't process the key on its own.
KeyEvent keyEvent = new KeyEvent(event.when, event.when,
down ? KeyEvent.ACTION_DOWN : KeyEvent.ACTION_UP,
                            code, keyRepeatCount);
mBroadcastWakeLock.acquire();
mHandler.post(new PassHeadsetKey(keyEvent));
}







